### PR TITLE
PLAT-11137 Fastlane Decoupled (Fastlane)

### PR DESCRIPTION
**Pull request by mabdullahabid**
## Ticket

PLAT-11137
_Related tickets:_
_Related PRs:_ https://github.com/crowdbotics/crowdbotics-slack-app/pull/4564 https://github.com/crowdbotics/modules/pull/894

## Type of PR

- [ ] Bugfix
- [x] New feature
- [ ] Minor changes

## Changes introduced

This PR decouples Fastlane config into a separate repo which can then be imported into project repos using the `import_from_git` command. We also make use of ruby instance variables in order to pass variables from the instantiated `Fastfile` object to the imported one.

Note: All three PRs need to be released together for this to work.

## Test and review

Refer to the Test and review section under https://github.com/crowdbotics/crowdbotics-slack-app/pull/4564

### CODE REVIEW

**Review by sgmagar — APPROVED** [review]
For testing this, we should do a release right?

**Comment by mabdullahabid** [comment]
> For testing this, we should do a release right?

There is a review app here https://cbdash-pr-4564.herokuapp.com/

**Comment by sgmagar** [comment]
> https://cbdash-pr-4564.herokuapp.com/

I saw version in the import section in this PR https://github.com/crowdbotics/modules/pull/894/files#diff-d304a6dca6895e89ddc866cc66cfa35cbf750b74653d0f914e691f36970848c6R20
This ties to the release tag right?

**Comment by mabdullahabid** [comment]
> > https://cbdash-pr-4564.herokuapp.com/
> 
> I saw version in the import section in this PR https://github.com/crowdbotics/modules/pull/894/files#diff-d304a6dca6895e89ddc866cc66cfa35cbf750b74653d0f914e691f36970848c6R20 This ties to the release tag right?

That is correct. Yes, once we release, we'll need to add a new environment variable to Heroku referring to the release version 1.0.0.

**Pull request merged**
